# Device name, used to differentiate cameras over networktables
device_id = "test"
# Map of apriltag location, copied from wpilib
map = "maps/2024-crescendo.json"
# Robot IP Address
server_ip = "10.60.36.2"

test_video = "testdata/2024speaker.webm"
use_networktables = true

# opencv, gstreamer
capture = "opencv"
# apriltag, aruco, wpilib
detector = "aruco"
# singletag, multitag, ransac
#solvepnp_method = "multitag_ap3p"
solvepnp_method = "ransac"
ignored_tags = []

[camera]
calibration = "calibration/002-7_1600x1200.json"
# Default GStreamer pipeline
pipeline = "v4l2src device=/dev/video0 extra_controls=\"c,exposure_dynamic_framerate=1\" ! image/jpeg,format=MJPG,width=1280,height=720 ! jpegdec ! appsink drop=1"
# Camera fps, used to estimate latency
fps = 50

[aruco]
# Do initial detection on a downscaled image, refine on original
# Higher decimate means lower detecion range, Lower means less performance
decimate = 1
# Use newer aruco3 algorithm
aruco3 = false
# none, subpix
corner_refinement = "subpix"
# Corner refinement window size for subpix
relative_refinement_window = 1
max_refinement_window = 5

[apriltag3]
border = 1
threads = 8
quad_decimate = 1.0
quad_blur = 0.0
refine_edges = true
refine_decode = false
refine_pose = false
debug = false
quad_contours = true

[logging]
enabled = true
# jpeg encoding quality (0-100)
quality = 25
# Maximum logged resolution (integer downscaled)
max_res = [ 1600, 1200 ]

[websockets]
enabled = true
# jpeg encoding quality (0-100)
quality = 25
# Maximum stream resolution (integer downscaled)
max_res = [ 800, 600 ]
