# Map of apriltag location, copied from wpilib
map = "assets/maps/2024-crescendo.json"
# Robot IP Address
team_number = 6036
use_networktables = true
dev_server_port = 5800

# apriltag, aruco
detector = "apriltag"
# singletag, multitag, ransac
solvepnp_method = "ransac"
ignored_tags = []

[camera]
brightness = 200
exposure = 800
gain = 16

[aruco]
# Do initial detection on a downscaled image, refine on original
# Higher decimate means lower detecion range, Lower means less performance
decimate = 1
# Use newer aruco3 algorithm
aruco3 = false
# none, subpix
corner_refinement = true
# Corner refinement window size for subpix
relative_refinement_window = 1
max_refinement_window = 5

[apriltag3]
families = "tag36h11"
border = 1
threads = 6
quad_decimate = 1.0
quad_sigma = 0.0
refine_edges = true
refine_decode = false
refine_pose = false
debug = false
quad_contours = true
decision_margin = 0
decode_sharpening = 0.25

[logging]
enabled = false
# jpeg encoding quality (0-100)
quality = 25
# Maximum logged resolution (integer downscaled)
max_res = [1600, 1200]

[http_stream]
enabled = true
# jpeg encoding quality (0-100)
quality = 90
# Maximum stream resolution (integer downscaled)
max_res = [640, 400]

[foxglove_server]
enabled = false
# jpeg encoding quality (0-100)
quality = 25
# Maximum stream resolution (integer downscaled)
max_res = [800, 600]
