version: '3.8'
services:
  perception:
    image: peninsula/perception:v0.1.0
    container_name: perception
    privileged: true
    network_mode: host
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - "/logs:/logs"
    restart: always
