version: '3.8'
services:
  perception:
    image: peninsula/perception:v0.1.0
    container_name: perception
    privileged: true
    network_mode: host
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - "/logs:/logs"
    restart: always
    environment:
      - DEVICE_ID=test
      - CALIBRATION_FILE=logs/003-4_1280x720.json
      - CAPTURE_METHOD=gstreamer
      - SOLVEPNP_MODE=ransac
