#!/usr/bin/env python3

import argparse
import json
import sys

import mrcal

parser = argparse.ArgumentParser("mrcal_converter")

parser.add_argument("filepath", help="Path to your .cameramodel file", type=str)
parser.add_argument("outputpath", help="Output filepath", type=str)
args = parser.parse_args()

try:
    model = mrcal.cameramodel(args.filepath)
except:
    print("Error loading calibration file:", args.filepath)
    sys.exit()

model_type, intrinsics_mrcal = model.intrinsics()

x_res, y_res = model.imagersize().tolist()

intrinsic_matrix_opencv = [
    [intrinsics_mrcal[0], 0, intrinsics_mrcal[2]],
    [0, intrinsics_mrcal[1], intrinsics_mrcal[3]],
    [0, 0, 1],
]

distortions_opencv = intrinsics_mrcal[4:].tolist()

calibration_out = {
    "resolution": [x_res, y_res],
    "cameraMatrix": intrinsic_matrix_opencv,
    "distCoeffs": distortions_opencv,
}

# Read the first few lines of the input file
with open(args.filepath, 'r') as file:
    file_header = ''.join([next(file) for _ in range(5)])

# Write the output to a TOML file
with open(args.outputpath, "w") as out:
    out.write("# Original file first lines:\n")
    out.write(file_header)
    out.write("\n")
    out.write("# Calibration data\n")
    out.write(toml.dumps(calibration_out))

