version: '3.8'
services:
  perception:
    image: peninsula/perception
    container_name: perception
    privileged: true
    network_mode: host
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - "/home/ubuntu/app:/app"
    restart: always
    environment:
      - DEVICE_ID=test
      - CAPTURE_METHOD=gstreamer
