name: Build project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up just
        uses: taiki-e/install-action@just

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Check connectivity frog
        run: ping -c 3 wpilib.jfrog.io || echo "Cannot reach wpilib.jfrog.io"
        

      - name: Check connectivity frog
        run: curl -I https://repo.lux-robotic.dev/simple/ || echo "Cannot reach lux-robotic.dev"


      - name: Build Project
        run: just package
